name: mseq_pipeline_py3.9
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.9
  
  # Core ML packages
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio
  - pytorch-cuda=12.1
  - pytorch-lightning
  
  # Scientific computing
  - numpy=1.26.4
  - scipy>=1.11,<1.14
  - scikit-learn
  - scikit-image
  - pandas
  - matplotlib
  
  # Image processing
  - opencv
  - pillow
  - libvips
  - imageio
  - tifffile
  
  # Data handling
  - openpyxl
  - xlsxwriter
  - beautifulsoup4
  - jsonlines
  - jsonschema
  
  # Development tools
  - pytest
  - jupyterlab
  - notebook
  - ipykernel
  
  # Other utilities
  - statsmodels
  - libxml2
  - cython
  - regex
  - termcolor
  - omegaconf
  - einops
  - glob2
  
  # Packages only available via pip
  - pip
  - pip:
      # ML-specific packages not in conda
      - segmentation-models-pytorch
      - pythae
      - lpips
      - piq
      # - sam2==1.1.0
      - supervision==0.25.0
      - transformers
      - safetensors
      - huggingface-hub
      - tokenizers

      # Specialized packages
      - aicsimageio
      - nd2
      - pyvips
      - pycocotools
      - stitch2d
      - submitit
      - iopath
      - portalocker
      
      # Development utilities
      - hydra-core
      - addict
      - colorlog
      - git-filter-repo
      - hf-xet
      - yapfw